services:
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    
  db:
    image: postgres:16
    container_name: postgres_c
    restart: unless-stopped
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: prd_milenio
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d prd_milenio"]
      timeout: 10s
      retries: 5
      interval: 10s
      start_period: 30s

  app:
    build: 
      context: .
    container_name: prj_medicos_c
    command: sh -c "\
            echo 'Postgres is ready - executing Django commands' &&\
            python manage.py makemigrations medicos &&\
            python manage.py migrate &&\
            python manage.py runserver 0.0.0.0:8000"
    restart: unless-stopped
    environment:
      SECONDARY_DATABASE_HOST: db  
      SECONDARY_DATABASE_NAME: prd_milenio
      SECONDARY_DATABASE_USER: admin
      SECONDARY_DATABASE_PASSWORD: admin
      SECONDARY_DATABASE_PORT: '5432'
      REDIS_HOST: redis
    volumes:
      - .:/app
      - ./static:/static
      - ./django_logs:/logs
    ports:
      - "8000:8000"
    depends_on: 
      db:
        condition: service_healthy
volumes:
  pgdata:
  django_logs:
  nginx_logs:
  static: