services:
  redis:
    image: "redis:alpine"
    
  db:
    image: mysql:8.0
    container_name: mysql_c
    restart: unless-stopped
    volumes:
      - ./db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: prd_milenio
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_ROOT_HOST: '%'
      MYSQL_AUTHENTICATION_PLUGIN: mysql_native_password
    command: >
      --default-authentication-plugin=mysql_native_password
      --bind-address=0.0.0.0
      --skip-name-resolve
      --sql_mode=""
      --skip-host-cache
      --explicit_defaults_for_timestamp=1
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot"]
      timeout: 10s
      retries: 5
      interval: 10s
      start_period: 80s

  app:
    build: 
      context: .
    container_name: medicos_c
    command: sh -c "
            echo 'MySQL is ready - executing Django commands' &&
            python manage.py migrate &&
            python manage.py makemigrations medicos &&
            python manage.py migrate &&
            python manage.py runserver 0.0.0.0:8000"
    restart: unless-stopped
    environment:
      SECONDARY_DATABASE_HOST: db  
      SECONDARY_DATABASE_NAME: prd_milenio
      SECONDARY_DATABASE_USER: admin
      SECONDARY_DATABASE_PASSWORD: admin
      SECONDARY_DATABASE_PORT: '3306'
      REDIS_HOST: redis
    volumes:
      - .:/app
      - ./static:/static
      - ./django_logs:/logs
    ports:
      - "8000:8000"
    depends_on: 
      db:
        condition: service_healthy
volumes:
  mysql_data:
  django_logs:
  nginx_logs:
  static: