services:
  redis:
    image: "redis:alpine"
  db:
    image: mysql:8.0
    container_name: mysql_c
    restart: unless-stopped
    volumes:
      - /tmp/app/mysqld:/var/run/mysqld
      - ./db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE     : db_medicos
      MYSQL_USER         : admin
      MYSQL_PASSWORD     : admin
    ports:
      - "3306:3306"
    healthcheck:
      test:  mysql --user=root --password=root -e "SELECT 1"
      timeout: 10s
      retries: 5

  app:
    image: miltoneo/medicos:latest                     # current directory
    container_name: medicos_c
    command: sh -c " python manage.py migrate 
                      && python manage.py makemigrations medicos 
                      && python manage.py migrate  
                      && gunicorn prj_medicos.wsgi:application --bind 0.0.0.0:8000 --workers 3
                      --access-logfile - --error-logfile - --log-level debug"

    restart: unless-stopped
    environment:
      #SECONDARY_SERVER_HOSTNAME: db 
      SECONDARY_SERVER_HOSTNAME: db #host.docker.internal  
      SECONDARY_DATABASE_NAME: db_medicos
      SECONDARY_DATABASE_USER: admin
      SECONDARY_DATABASE_PASSWORD: admin
      SECONDARY_DATABASE_PORT    : '5432'
      REDIS_HOST: redis
    volumes:
      - .:/app
      - ./static:/static
      - ./django_logs:/logs
    ports:
      - "8000:8000"
    depends_on: 
      db:
        condition: service_healthy
