services:
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    
  db:
    image: postgres:16
    container_name: postgres_c
    restart: unless-stopped
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: db_medicos
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d db_medicos"]
      timeout: 10s
      retries: 5
      interval: 10s
      start_period: 30s


  app:
    image: miltoneo/prj_medicos:latest
    container_name: prj_medicos_c
    command: sh -c " python manage.py migrate 
                      && python manage.py makemigrations medicos 
                      && python manage.py migrate  
                      && gunicorn prj_medicos.wsgi:application --bind 0.0.0.0:8000 --workers 3
                      --access-logfile - --error-logfile - --log-level debug"

    restart: unless-stopped
    environment:
      SECONDARY_SERVER_HOSTNAME: db #host.docker.internal  
      SECONDARY_DATABASE_NAME: db_medicos
      SECONDARY_DATABASE_USER: admin
      SECONDARY_DATABASE_PASSWORD: admin
      SECONDARY_DATABASE_PORT    : '5432'
      REDIS_HOST: redis
    volumes:
      - .:/app
      - ./static:/static
      - ./django_logs:/logs
    ports:
      - "8000:8000"
    depends_on: 
      db:
        condition: service_healthy
